CleanStudentManagementUI/Controllers/ExamController.cs
using CleanStudentManagementBLL.Services;
using CleanStudentManagementModel;
using CleanStudentManagementUI.Filter;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CleanStudentManagementUI.Controllers
{
    [RoleAuthorize(2)]
    public class ExamController : Controller
    {
        private readonly IGroupService _groupservices;
        private readonly IExamService _examservices;

        public ExamController(IGroupService groupservices, IExamService examservices)
        {
            _groupservices = groupservices;
            _examservices = examservices;
        }

        public IActionResult Index(int pageno = 1, int pagesize = 3)
        {
            var examdata = _examservices.GetAllExam(pageno, pagesize);
            return View(examdata);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var groups = _groupservices.GetAllGroups();
            ViewBag.GetAllgrps = new SelectList(groups, "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateExamModel examModel)
        {
            _examservices.AddExam(examModel);
            return RedirectToAction("Index");
        }
    }
}

CleanStudentManagementUI/Controllers/GroupController.cs
using CleanStudentManagementBLL.Services;
using CleanStudentManagementModel;
using Microsoft.AspNetCore.Mvc;

namespace CleanStudentManagementUI.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly IStudentService _studentService;

        public GroupController(IGroupService groupService, IStudentService studentService)
        {
            _groupService = groupService;
            _studentService = studentService;
        }

        public IActionResult Index(int pageno = 1, int pagesize = 3)
        {
            var groupdata = _groupService.GetAll(pageno, pagesize);
            return View(groupdata);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(GroupViewModel groupView)
        {
            _groupService.AddGroup(groupView);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            GroupStudentViewModel groupStudent = new GroupStudentViewModel();
            var group = _groupService.GetById(id);
            var students = _studentService.GetAll();
            groupStudent.GroupId = group.Id;
            foreach (var student in students)
            {
                var studentinfo = new Checkboxtable()
                {
                    Id = student.Id,
                    Name = student.Name,
                    IsChecked = student.GroupId == null ? false : true
                };
                groupStudent.StudentList.Add(studentinfo);
            }
            return View(groupStudent);
        }
        [HttpPost]
        public IActionResult Details(GroupStudentViewModel gsmodel)
        {
            bool result = _studentService.SetGroupIdToStudent(gsmodel);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(gsmodel);
        }
    }
}

CleanStudentManagementUI/Controllers/QuesAnsController.cs
using CleanStudentManagementBLL.Services;
using CleanStudentManagementModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CleanStudentManagementUI.Controllers
{
    public class QuesAnsController : Controller
    {
        private readonly IExamService _examservice;
        private readonly IQnAnsService _iqnAnsservice;
        public QuesAnsController(IExamService examservice, IQnAnsService iqnAnsservice)
        {
            _examservice = examservice;
            _iqnAnsservice = iqnAnsservice;
        }

        public IActionResult Index(int pageno=1, int pagesize=3)
        {
            var queslist = _iqnAnsservice.GetAllQans(pageno, pagesize);
            return View(queslist);
        }
        public IActionResult Create()
        {
            var exams = _examservice.GetAll();
            ViewBag.Examlist = new SelectList(exams, "Id", "Title");
            return View();
        }
        [HttpPost]
        public IActionResult Create(QAnsViewModel ansViewModel)
        {
            _iqnAnsservice.Add(ansViewModel);
            return RedirectToAction("Index");
        }
    }
}

CleanStudentManagementUI/Controllers/UsersController.cs
using CleanStudentManagementBLL.Services;
using CleanStudentManagementModel;
using CleanStudentManagementUI.Filter;
using Microsoft.AspNetCore.Mvc;

namespace CleanStudentManagementUI.Controllers
{
    [RoleAuthorize(1)]
    public class UsersController : Controller
    {
        private readonly IAccountService _accountservice;

        public UsersController(IAccountService accountservice)
        {
            _accountservice = accountservice;
        }

        public IActionResult Index(int Pagenumber = 1,int pagesize=2)
        {
            var teacherdata = _accountservice.GetAll(Pagenumber, pagesize);
            return View(teacherdata);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(UserViewModel userView)
        {
            var success = _accountservice.AddTeacher(userView);
            if (success)
            {
                return RedirectToAction("Index");
            }
            return View(userView);
        }
    }
}

CleanStudentManagementUI/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json
@inject IHttpContextAccessor contextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CleanStudentManagementUI</title>
    <link href="~/css/united.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CleanStudentManagementUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @if (contextAccessor.HttpContext?.Session.GetString("logindetails")!=null)
        {
            var sessaioninfo = contextAccessor.HttpContext.Session.GetString("logindetails");
            var logindata = JsonConvert.DeserializeObject<LoginViewModel>(sessaioninfo);
            if (logindata?.Role==1)
            {
                <partial name="_adminNav"/>
            }
            if (logindata?.Role == 2)
            {
                <partial name="_teacherNav" />
            }
            if (logindata?.Role == 3)
            {
                <partial name="_studentNav" />
            }
        }
        else
        {
            <partial name="_defaultNav" />
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CleanStudentManagementUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CleanStudentManagementUI/Views/Shared/_adminNav.cshtml
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Admin CMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" asp-action="Index" asp-controller="Home">
                        Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Users">Teachers</a>
                </li>
               <li class="nav-item">
                    <a class="nav-link" asp-action="Index"asp-controller="Group">Classes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Student">Students</a>
                </li>
                @*  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li> *@
            </ul>
            <partial name="_LoginPartial"/>
        </div>
    </div>
</nav>

CleanStudentManagementUI/Views/Shared/_defaultNav.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Management</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

CleanStudentManagementUI/Views/Shared/_studentNav.cshtml
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Student CMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="#">
                        Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Profile"asp-controller="Student">My Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="AttendExam" asp-controller="Student">Attend Exam</a>
                </li>
               @*  <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
 *@            </ul>
            @* <form class="d-flex">
                <input class="form-control me-sm-2" type="search" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form> *@
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

CleanStudentManagementUI/Views/Shared/_teacherNav.cshtml
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Teacher CMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="#">
                        Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Exam" asp-action="Index">Exam</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="QuesAns" asp-action="Index">Exam Paper</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-sm-2" type="search" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>